### PR TITLE
Python 3 conversion

### PR DESCRIPTION
**Pull request by MichaelGoodale**
This merge converts the python scripts to python 3 from python 2.

There's a couple changes besides simply converting the two, there were occasional errors in the included textgrid helper file, so I updated the scripts to use [textgrid.py](https://github.com/kylebgorman/textgrid) instead. 

Additionally one change that was a matter of taste is that currently CSV output in `auto_vot_decode.py` now restricts precision to 12 digits(like python 2). This was so that the output was identical to the python 2 version(e.g. for tests in Conch). 

The code isn't entirely idiomatic to python 3, but it is now totally compatible with python 3.

### CODE REVIEW

**Comment by MichaelGoodale** [comment]
@msonderegger @jkeshet

**Comment by jkeshet** [comment]
Are these changes allow the usage of Python 2 AND Python 3?

**Comment by msonderegger** [comment]
@MichaelGoodale I don't think so, but this can be done by just adding the lines in "To convert existing Python 3 code" at the top of each script:

https://python-future.org/quickstart.html

**Comment by msonderegger** [comment]
I am going to merge this because this issue is blocking @mmcauliffe doing something in another repo, but @MichaelGoodale please do make Py 3/2 compatible, thanks!  The reason is that a non-trivial number of users have existing pipelines they use AUtoVOT in which assume Python2.

**Pull request merged**
